### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by y4my4my4m** [opicron/mysticbbs-irc#5]
## Issue
Can't connect to any server. 
SSL or not.
This is the error message on first attempt of servers I've never connected to.

## Environment
Mystic v1.12 alpha 48
Ubuntu 20
Python2.7
Netrunner client
Non-SSL server, telnet connection

## Installation/File structure
/mystic/themes/mytheme/scripts/irc.mpy
/mystic/themes/mytheme/scripts/irc/config.py
/mystic/themes/mytheme/scripts/irc/pager.ans
/mystic/themes/mytheme/scripts/irc/irc_help.ans
/mystic/themes/mytheme/scripts/irc/chat.ans

I'm not using the pager. function

## Screenshot
![image](https://github.com/opicron/mysticbbs-irc/assets/8145020/627e818f-a198-4722-bed9-e95b02696a8e)

**Comment by y4my4my4m** [comment]
@opicron any idea what the issue might be?
Cheers

**Comment by y4my4my4m** [comment]
I might have found the issue...it's somehow looking in the `themes/default/scripts/irc` folder? might be my mystic configs...

**Comment by y4my4my4m** [comment]
Ok, a few things:

1. I've renamed my customtheme to default, lol
2. **it doesn't recognize my irc/config.py, why? Yet the only server config it seems to recognize is when i modify irc.mpy and change the default server there**
3. The "too many connections from your IP comes from your irc.opicron server
4. Some other server didn't like my username, i was finally able to connect on darkmyst.org

So, all in all, it's mostly functional, I'd just like help figuring out why it won't use irc/config.py?
Refer to the first post to see my filestructure (except now it's all in default).

**Comment by opicron** [comment]
Odd, its seems to work here fine. Maximum simultanous IPs is 10. So it should not happen easily. Thanks for your thorough checking.

Could the configuration issue be a file rights issue?
