### ISSUE TITLE
"Connection Closed By Foreign Host" Error.

### ISSUE THREAD

**Issue by techcat-dev** [opicron/mysticbbs-irc#6]
Attempting to execute the script disconnects the user from the BBS.
I have mystic installed on /mystic/ and have copied over all of the scripts and renamed the, as described in the readme.txt. however, I have not edited the config file yet. 
I'm new to Mystic and BBS in general. any help is appreciated. I'm connected to my BBS server through TELNET.

![image](https://github.com/opicron/mysticbbs-irc/assets/143054835/cfd31caf-9d15-4d06-b934-546b98227075)

**Comment by opicron** [comment]
Did you use the latest github version? Go through the configuration file and see if all is correct.

**Comment by opicron** [comment]
I improved error catching and this should not happpen again.
