### ISSUE TITLE
Listen thread exception

### ISSUE THREAD

**Issue by vbchrisrj** [opicron/mysticbbs-irc#7]
I had a user attempt to join the #spacex room on EFnet and they received the following error:

Listen thread exception: Traceback (most recent call last):  File "/mystic/themes/CJs/scripts/irc.mpy", line 1164, in thread_listen    command = args.pop(0)IndexError: pop from empty list

This appears to be the only one that is having an issue.  The connection information is:

host     [4] = "irc.deft.com"
port     [4] = 6667
channel  [4] = "#spacex"
srvpass  [4] = ""
password [4] = ""
ssl      [4] = False

I'm pretty sure that this was working fine at one point. I tested each of the options that I had setup, when I set them up.  I tried it after the user hung up and received the same error message.

**Comment by opicron** [comment]
Let me test this tomorrow.

**Comment by opicron** [comment]
Im am connected without issue here.

![Screenshot 2024-08-15 115856](https://github.com/user-attachments/assets/778ab9b5-d342-4a76-b4e4-51e5516bc9fa)

**Comment by opicron** [comment]
I added exception catch for sockets and the user notification should be improved now.

**Comment by opicron** [comment]
By they way, you might want to connect to port 9999 and put SSL on True. That way your users chats are at least not send as plaintext over the internet.
